@startuml

!includeurl  https://raw.githubusercontent.com/DBuret/myjournal/master/plantuml.cfg

rectangle DMZ << dmz >> {
    rectangle "<$reverse_proxy>\nReverse Proxy\nIPS/IDS" << serveur >> as ReverseProxy
}

rectangle "Servers LAN"  << dmz >>  as lan {
    rectangle "<$web_server>\nApplication" as App
    rectangle "<$database_server>Redis"  as redis
    rectangle "<$server_farm>\nCompute"  as hpc
    rectangle "<$database_availability_group>\nDatabase"  as db
    rectangle "<$file_server>\nNAS"  as nas
}

rectangle "Admin LAN"  << dmz >>  as adminlan {
    rectangle "<$cluster_server>\nBastion" as bastion
}

rectangle "<$firewall>\nexternal firewall"   as fwe
rectangle "<$firewall>\ninternal firewal" as fwi
rectangle "<$firewall>\nadmin firewall E"  as fwa
rectangle "<$firewall>\nadmin firewall I"  as fwai


rectangle "<$users>\nInternet Users"  as users
rectangle "<$users>\nOffices Users"  as office

rectangle "<$globe_internet>Internet" as internet
rectangle "<$cloud>\nWAN"  as wan

rectangle "<$administrator>\nAdmins" as Admins

'user flow'
users .> internet << https >> : 2
internet .> fwe << https >>: 2

office -l-> wan << https >> : 1 
wan -l-> fwe << https >> : 1 

fwe ..> ReverseProxy << https >> : "1+2"

ReverseProxy .> fwi << http >> : 3
fwi ..> App << http >> : 3

'app flows'
App --> db << jdbc >> : 4 
App --> hpc << flow >> : 6
App --> redis << flow >> : 5
App --> nas << nfs >>  : 7

'admin flows'
Admins ~> fwa << ssh >> : a 
fwa ~> bastion << ssh >> : a
Admins -[hidden]-> bastion << ssh >>
bastion -u-> fwai << ssh >> : b
fwai -u-> App << ssh >> : b
fwai -u-> db << ssh >> : b
fwai -u-> hpc << ssh >> : b
fwai -u-> redis << ssh >> : b
fwai -u-> nas << https >> : b

@enduml